export type Idioma = "es" | "en";

export const telefonoWhatsApp = "34631596309";
export const telefonoFormateado = "+34 631 59 63 09";
export const emailContactobarco = "leonsailingtenerife@gmail.com";
export const webContactoalquiler = "mlteneriferealestate.com";

export const fotosGaleria = [
  {
    src: "/media/leon/leon-sailing-tenerife.jpg",
    alt: {
      es: "El velero Leon navegando a vela frente a la costa sur de Tenerife",
      en: "Leon sailing off the south coast of Tenerife",
    },
    label: { es: "Navegando frente a Tenerife", en: "Sailing off Tenerife" },
    tag: { es: "Exterior", en: "Exterior" },
  },
  {
    src: "/media/leon/leon-salon.jpg",
    alt: {
      es: "Salón principal de Leon con cocina y mesa interior",
      en: "Leon's main saloon with galley and indoor dining table",
    },
    label: { es: "Salón principal", en: "Main saloon" },
    tag: { es: "Interior", en: "Interior" },
  },
  {
    src: "/media/leon/leon-cabin.jpg",
    alt: {
      es: "Camarote doble preparado en el interior del velero Leon",
      en: "Double cabin prepared inside Leon",
    },
    label: { es: "Camarote doble", en: "Double cabin" },
    tag: { es: "Interior", en: "Interior" },
  },
  {
    src: "/media/leon/leon-exterior-marina.jpg",
    alt: {
      es: "Vista exterior del velero Leon amarrado en el puerto",
      en: "Exterior view of Leon moored in the marina",
    },
    label: { es: "Leon en puerto", en: "Leon in the marina" },
    tag: { es: "Exterior", en: "Exterior" },
  },
  {
    src: "/media/leon/leon-cockpit.jpg",
    alt: {
      es: "Zona exterior de Leon con mesa y asientos para disfrutar en cubierta",
      en: "Leon's outdoor seating area with a table, prepared for time on deck",
    },
    label: { es: "Zona exterior con mesa y asientos", en: "Outdoor seating with table" },
    tag: { es: "Exterior", en: "Exterior" },
  },
  {
    src: "/media/leon/leon-dining.jpg",
    alt: {
      es: "Mesa del comedor interior de Leon preparada para cuatro personas",
      en: "Leon's indoor dining table prepared for four people",
    },
    label: { es: "Comedor interior", en: "Indoor dining" },
    tag: { es: "Interior", en: "Interior" },
  },
  {
    src: "/media/tenerife/los-gigantes.jpg",
    alt: {
      es: "Acantilados y puerto de Los Gigantes vistos desde el aire",
      en: "Los Gigantes cliffs and marina seen from above",
    },
    label: { es: "Los Gigantes", en: "Los Gigantes" },
    tag: { es: "Tenerife", en: "Tenerife" },
  },
  {
    src: "/media/tenerife/atlantic-dolphins.jpg",
    alt: {
      es: "Delfines nadando en libertad en el océano Atlántico",
      en: "Wild dolphins swimming in the Atlantic Ocean",
    },
    label: { es: "Fauna del Atlántico", en: "Atlantic wildlife" },
    tag: { es: "Tenerife", en: "Tenerife" },
  },
];

export const textos = {
  es: {
    skipContent: "Saltar al contenido",
    navInicio: "Inicio",
    navExperiencia: "La experiencia",
    navBarco: "Leon",
    navRuta: "Marina del Sur",
    navPatron: "Patrón",
    navPrecios: "Precios",
    navReservas: "Disponibilidad",
    navNosotros: "Sobre nosotros",
    navGuia: "Guía",
    navFaq: "Preguntas",
    menuAbrir: "Abrir menú",
    menuCerrar: "Cerrar menú",
    idiomaLabel: "Idioma",
    musicaActivar: "Activar música",
    musicaPausar: "Silenciar música",

    slogan: "Excursiones y alquiler privado · Tenerife",
    titulo1: "Tenerife se vive",
    titulo2: "desde el mar",
    descripcion: "Una experiencia privada a bordo de Leon: 12 metros de vela, costa volcánica y el Atlántico a vuestro ritmo.",
    heroPrimary: "Descubrir fechas",
    headerReserve: "Reservar",
    btnWhatsapp: "Hablar por WhatsApp",
    btnEmail: "Escribir por email",
    heroNote: "Reserva directa y atención personal, de principio a fin.",
    derechos: "Todos los derechos reservados.",
    mensajeWa: "¡Hola! Me gustaría consultar una excursión privada de 6 horas, un alquiler de 3 días o más, o el día de instrucción a bordo de Leon. ¿Podéis indicarme disponibilidad?",
    asuntoEmail: "Consulta%20de%20chárter%20privado%20a%20bordo%20de%20Leon",

    factPrivateValue: "Solo vosotros",
    factPrivateLabel: "Privacidad a bordo",
    factLengthValue: "12 m",
    factLengthLabel: "Velero Leon",
    factLocationValue: "Las Galletas",
    factLocationLabel: "Marina del Sur",
    factDirectValue: "Personal",
    factDirectLabel: "Atención directa",
    factOverallLengthValue: "11,67 m",
    factOverallLengthLabel: "Eslora total",
    factBeamValue: "3,82 m",
    factBeamLabel: "Manga",
    factCabinsValue: "3",
    factCabinsLabel: "Camarotes",
    factBathroomValue: "1",
    factBathroomLabel: "Baño",

    expPre: "Una experiencia a vuestra medida",
    expTitle: "El privilegio de navegar sin prisas",
    expDesc: "Leon no funciona con salidas en serie. Escuchamos el plan que imagináis y diseñamos una propuesta privada, cuidada y coherente con el viento, el mar y el tiempo que queréis pasar a bordo.",
    expPrivateTitle: "El barco, solo para vosotros",
    expPrivateDesc: "Sin grupos compartidos ni desconocidos a bordo. El espacio, el ritmo y cada momento pertenecen a vuestra compañía.",
    expRouteTitle: "Una ruta con sentido",
    expRouteDesc: "Cada travesía se plantea con criterio marinero, combinando vuestros deseos con las mejores condiciones del día.",
    expWildlifeTitle: "El Atlántico, en primera fila",
    expWildlifeDesc: "Costa volcánica, calas, horizontes abiertos y la posibilidad de encontrar fauna marina en libertad.",


    secUbicacion: "Nuestra base en Tenerife",
    ubiPuertoTitulo: "Marina del Sur, junto al corazón de Las Galletas",
    ubiPuertoDesc: "Leon tiene su amarre en Marina del Sur, a unos 20 minutos del Aeropuerto de Tenerife Sur. El puerto está junto al pueblo de Las Galletas, por lo que al dejar el barco amarrado encontraréis restaurantes, cafeterías y otros servicios a pocos minutos a pie.",
    ubiRutasTitulo: "Un puerto cómodo, conectado y abierto al Atlántico",
    ubiRutasDesc: "Marina del Sur reúne acceso sencillo, servicios náuticos y la cercanía de Las Galletas. Es un punto de partida práctico para llegar, preparar la jornada y pasar del amarre al mar sin complicaciones.",
    routeNote: "Al confirmar la reserva recibiréis la ubicación exacta del amarre, el punto de encuentro y las indicaciones necesarias para llegar con facilidad.",
    routeVisualLabel: "Marina del Sur · Las Galletas",
    routeVisualAlt: "Vista aérea de Marina del Sur y el pueblo de Las Galletas en la costa sur de Tenerife",
    routeDesignPre: "Todo cerca antes de zarpar",
    routeDepartureTitle: "A 20 minutos del aeropuerto",
    routeDepartureDesc: "Una llegada sencilla desde el Aeropuerto de Tenerife Sur.",
    routeDurationTitle: "Las Galletas a pocos pasos",
    routeDurationDesc: "Restaurantes, cafeterías y servicios junto al puerto.",
    routeConditionsTitle: "Acceso directo al Atlántico",
    routeConditionsDesc: "Desde el amarre, la navegación comienza frente a la costa sur de Tenerife.",
    routeMapCta: "Abrir ubicación en Maps",
    routeFlexibleLabel: "Nuestra base",
    routeDepartureBadge: "Marina del Sur · Las Galletas",
    routeHeroTitle: "Aquí empieza vuestra experiencia con Leon",
    routeHeroDesc: "El velero os espera en Marina del Sur, junto al pueblo y frente al Atlántico. Un punto de encuentro cómodo para llegar, subir a bordo y comenzar a navegar.",

    helmPre: "La modalidad adecuada para cada servicio",
    helmTitle: "Excursión con capitán o alquiler con y sin patrón",
    helmDesc: "La excursión privada de 6 horas se realiza siempre con el capitán. Para alquileres de un mínimo de 3 días podéis contratar patrón o navegar sin patrón si acreditáis la experiencia y titulación necesarias.",
    helmCaptainTitle: "Francesco Gestri, armador y patrón de Leon",
    helmCaptainDesc: "Con más de 20 años navegando, Francesco es patrón de Marina Mercante y acompaña personalmente la experiencia. Habla español, italiano e inglés.",
    helmGuestTitle: "Titulación internacional",
    helmGuestDesc: "Dispone de la titulación Yacht Master Offshore Commercial y de titulaciones deportivas náuticas italianas y españolas.",
    helmSafetyTitle: "Alquiler sin patrón",
    helmSafetyDesc: "Disponible desde 3 días, con seis plazas para dormir y sujeto a la comprobación previa de la experiencia y titulación náutica de quien vaya a gobernar el velero.",

    instructionPre: "Formación a bordo",
    instructionPriceLabel: "Día de instrucción",
    instructionPrice: "200 €",
    instructionTax: "Precio publicado · IGIC incluido",
    instructionSchedule: "De 9:00 a 17:00",

    secGaleriaPre: "El velero",
    secGaleriaTitulo: "Conoce a Leon",
    secGaleriaDesc: "Descubre cada espacio de Leon, desde la cubierta y la navegación a vela hasta el salón, el comedor y los camarotes. Todas las fotografías muestran el barco y el entorno real de la experiencia.",
    galeriaAbrir: "Ampliar fotografía",
    galeriaCerrar: "Cerrar fotografía",
    galeriaAnterior: "Fotografía anterior",
    galeriaSiguiente: "Fotografía siguiente",

    videoPre: "Leon en movimiento",
    videoTitle: "La vela, el viento y Tenerife en un solo plano",
    videoDesc: "Una mirada aérea real a Leon navegando junto a la costa sur. Sin artificios: el azul del Atlántico, la silueta de la isla y el ritmo natural de una jornada a vela.",
    videoNote: "Imágenes aéreas reales de Leon en Tenerife",
    videoPlay: "Reproducir vídeo",
    videoPause: "Pausar vídeo",
    storyVisualAlt: "El velero Leon navegando frente a la costa de Tenerife",

    reserveBandPre: "Reserva directa",
    reserveBandTitle: "Vuestro día en el mar empieza con una fecha",
    reserveBandDesc: "Elegid entre una excursión privada de 6 horas, un alquiler de 3 días o más o el día de instrucción. Respondemos personalmente con disponibilidad y condiciones, sin intermediarios.",
    reserveBandCalendar: "Ver disponibilidad",
    reserveBandWhatsapp: "Consultar por WhatsApp",
    reserveBandCall: "Llamar ahora",
    reserveHelpTitle: "¿Preferís hablarlo antes de elegir?",
    reserveHelpDesc: "Escribidnos o llamadnos. Os ayudaremos a elegir entre la excursión de 6 horas, el alquiler desde 3 días y el día de instrucción.",
    reserveResponse: "Atención directa y respuesta personal",

    calPre: "Empieza a imaginar vuestro día",
    calTitulo: "Elegid vuestra experiencia. El calendario hará el resto.",
    calDesc: "Seleccionad primero la excursión, el día de instrucción o el alquiler y su duración. El calendario mostrará únicamente fechas que permitan completar el plan elegido.",
    bookingPrivate: "El velero completo para vuestro grupo",
    bookingDirect: "Reserva directa, sin comisiones de plataforma",
    bookingPersonal: "Con patrón o sin patrón, según experiencia y titulación",
    bookingPromiseTitle: "Reserva clara, directa y personal",
    bookingPromiseDesc: "Sin plataformas ni respuestas automáticas. Habláis directamente con nosotros desde la primera consulta hasta el día de la salida.",
    processOne: "Elegid el servicio y, si es un alquiler, indicad cuántos días necesitáis.",
    processTwo: "Seleccionad una fecha compatible e indicad las personas y los detalles del plan.",
    processThree: "Recibiréis una propuesta clara con opciones, precio y próximos pasos.",

    secHistoria: "Sobre nosotros",
    histSub: "Somos Francesco Gestri y Maureen Lacchini. El mar forma parte de nuestra historia.",
    histP1: "Somos marido y mujer y nos conocimos durante unas vacaciones en velero en Italia. Desde entonces, navegar se convirtió en una forma de vida que hoy compartimos con nuestra hija Isabel y con quienes llegan a Tenerife buscando una experiencia más personal.",
    histP2: "Francesco, armador y patrón de Leon, aporta más de 20 años de navegación y sus titulaciones de Marina Mercante y Yacht Master Offshore Commercial. Maureen cuida la atención cercana y los detalles que hacen acogedora cada salida. Juntos queremos que os sintáis seguros y verdaderamente bienvenidos a bordo.",
    storySignature: "Somos Francesco y Maureen. Bienvenidos a bordo de Leon.",
    secInmo: "Tenerife, también para quedarse",

    guidePre: "Antes de zarpar",
    guideTitle: "Todo lo necesario para disfrutar del día",
    guideDesc: "Al confirmar la salida recibiréis los detalles definitivos. Mientras tanto, estas recomendaciones os ayudarán a llegar preparados y cómodos.",
    guideOneTitle: "Ropa cómoda",
    guideOneDesc: "Traed prendas ligeras y una chaqueta fina. En el mar la sensación térmica puede cambiar incluso en días soleados.",
    guideTwoTitle: "Calzado adecuado",
    guideTwoDesc: "Recomendamos calzado plano, limpio y con suela antideslizante. Evitad tacones y suelas que puedan marcar la cubierta.",
    guideThreeTitle: "Protección solar",
    guideThreeDesc: "Protector solar, gafas de sol y gorra son esenciales. Una toalla y bañador completan el equipaje para las paradas de baño.",
    guideFourTitle: "Llegada al puerto",
    guideFourDesc: "Llegad unos 15 minutos antes. Os enviaremos el punto de encuentro exacto y las indicaciones de acceso tras confirmar la reserva.",
    guideFiveTitle: "Mareo y salud",
    guideFiveDesc: "Si soléis marearos, consultad previamente con un profesional sanitario sobre la opción adecuada para vosotros y avisadnos de cualquier necesidad relevante.",
    guideSixTitle: "Equipaje y documentación",
    guideSixDesc: "Mejor una bolsa pequeña y flexible. Llevad identificación y comunicad con antelación alergias, movilidad reducida o necesidades especiales.",

    faqPre: "Preguntas frecuentes",
    faqTitle: "Todo lo importante, con claridad",
    faqQ1: "¿Seleccionar una fecha confirma la reserva?",
    faqA1: "No. La selección abre una consulta sin compromiso. Os confirmaremos disponibilidad, propuesta, precio y condiciones antes de formalizar la reserva.",
    faqQ2: "¿Desde dónde zarpa Leon?",
    faqA2: "Desde Marina del Sur, en Las Galletas. Una vez confirmada la salida, os enviaremos el punto de encuentro exacto y las indicaciones de acceso.",
    faqQ3: "¿La ruta se decide con antelación?",
    faqA3: "La ruta se prepara según el servicio elegido y vuestros intereses. El recorrido definitivo se confirma cerca de la salida, siempre en función del viento y del estado del mar.",
    faqQ4: "¿Cómo recibo opciones y precio?",
    faqA4: "Elegid una fecha y seleccionad la excursión de 6 horas, el alquiler desde 3 días o el día de instrucción. También podéis escribirnos directamente por WhatsApp.",
    faqQ5: "¿Puedo alquilar Leon sin patrón?",
    faqA5: "Sí, únicamente en alquileres de un mínimo de 3 días y siempre que acreditéis la experiencia y titulación náutica necesarias. La excursión de 6 horas y el día de instrucción se realizan con capitán o instructor a bordo.",
    faqQ6: "¿Qué incluye la excursión privada?",
    faqA6: "El precio publicado de 600 € incluye seis horas de excursión, capitán, almuerzo, fondeo, equipo de snorkel, seguro, canon de pasajeros e IGIC. Admite hasta ocho pasajeros, además del patrón.",
    faqQ7: "¿Qué equipamiento de seguridad lleva Leon?",
    faqA7: "Leon dispone del equipamiento exigido por la normativa: chalecos salvavidas suficientes para todos, seis chalecos autoinflables para alquileres largos, balsa salvavidas, radiobaliza automática, bengalas, botiquín, extintores, aro salvavidas y líneas de vida.",

    whatsappFloatEyebrow: "¿Tienes alguna duda?",
    whatsappFloatLabel: "Escríbenos por WhatsApp",

    ctaEyebrow: "Vuestra próxima historia empieza aquí",
    ctaFinal: "¿Cuándo queréis subir a bordo?",
    ctaDesc: "Decidnos la fecha, cuántas personas sois y la idea que tenéis en mente. Nosotros la convertiremos en una propuesta para navegar.",
    mobileCta: "Ver fechas disponibles",
    footerTagline: "Experiencias privadas de navegación desde Marina del Sur, Tenerife.",
    footerContact: "Contacto directo",
    avisoLegal: "Aviso legal",
    privacidad: "Privacidad",
    cookies: "Cookies",
  },
  en: {
    skipContent: "Skip to content",
    navInicio: "Home",
    navExperiencia: "The experience",
    navBarco: "Leon",
    navRuta: "Marina del Sur",
    navPatron: "Skipper",
    navPrecios: "Prices",
    navReservas: "Availability",
    navNosotros: "About us",
    navGuia: "Guide",
    navFaq: "FAQ",
    menuAbrir: "Open menu",
    menuCerrar: "Close menu",
    idiomaLabel: "Language",
    musicaActivar: "Turn music on",
    musicaPausar: "Mute music",

    slogan: "Private excursions and yacht rental · Tenerife",
    titulo1: "Tenerife feels different",
    titulo2: "from the sea",
    descripcion: "A private experience aboard Leon: 12 metres of sailing, volcanic coastline and the Atlantic at your own pace.",
    heroPrimary: "Explore available dates",
    headerReserve: "Book now",
    btnWhatsapp: "Chat on WhatsApp",
    btnEmail: "Send an email",
    heroNote: "Direct booking and personal care, from first message to final mooring.",
    derechos: "All rights reserved.",
    mensajeWa: "Hello! I would like to enquire about a private 6-hour excursion, a yacht rental of 3 days or more, or the training day aboard Leon. Could you share availability?",
    asuntoEmail: "Private%20charter%20enquiry%20aboard%20Leon",

    factPrivateValue: "Just your group",
    factPrivateLabel: "Privacy on board",
    factLengthValue: "12 m",
    factLengthLabel: "Sailing yacht Leon",
    factLocationValue: "Las Galletas",
    factLocationLabel: "Marina del Sur",
    factDirectValue: "Personal",
    factDirectLabel: "Direct service",
    factOverallLengthValue: "11.67 m",
    factOverallLengthLabel: "Overall length",
    factBeamValue: "3.82 m",
    factBeamLabel: "Beam",
    factCabinsValue: "3",
    factCabinsLabel: "Cabins",
    factBathroomValue: "1",
    factBathroomLabel: "Bathroom",

    expPre: "An experience shaped around you",
    expTitle: "The privilege of sailing without rushing",
    expDesc: "Leon is not built around production-line departures. We listen to the day you have in mind and create a private, thoughtful proposal that respects the wind, the sea and the time you wish to spend on board.",
    expPrivateTitle: "The yacht is entirely yours",
    expPrivateDesc: "No shared groups and no strangers on board. The space, the pace and every moment belong to the people you choose.",
    expRouteTitle: "A route with purpose",
    expRouteDesc: "Each passage is planned with sound seamanship, balancing your wishes with the best conditions of the day.",
    expWildlifeTitle: "The Atlantic, front row",
    expWildlifeDesc: "Volcanic coastline, quiet coves, open horizons and the chance to encounter marine wildlife in its natural habitat.",


    secUbicacion: "Our Tenerife base",
    ubiPuertoTitulo: "Marina del Sur, beside the heart of Las Galletas",
    ubiPuertoDesc: "Leon is moored at Marina del Sur, around 20 minutes from Tenerife South Airport. The marina is beside the village of Las Galletas, so once the yacht is safely moored you will find restaurants, cafés and other amenities just a short walk away.",
    ubiRutasTitulo: "A convenient, connected marina open to the Atlantic",
    ubiRutasDesc: "Marina del Sur combines easy access, marine services and the convenience of Las Galletas nearby. It is a practical starting point for arriving, preparing for the day and moving from the berth to open water with ease.",
    routeNote: "Once your booking is confirmed, we will send the yacht's exact berth, meeting point and everything you need for an effortless arrival.",
    routeVisualLabel: "Marina del Sur · Las Galletas",
    routeVisualAlt: "Aerial view of Marina del Sur and the village of Las Galletas on Tenerife's south coast",
    routeDesignPre: "Everything close before you sail",
    routeDepartureTitle: "20 minutes from the airport",
    routeDepartureDesc: "An easy journey from Tenerife South Airport.",
    routeDurationTitle: "Las Galletas on your doorstep",
    routeDurationDesc: "Restaurants, cafés and useful services beside the marina.",
    routeConditionsTitle: "Direct access to the Atlantic",
    routeConditionsDesc: "From the berth, your sailing begins off Tenerife's south coast.",
    routeMapCta: "Open location in Maps",
    routeFlexibleLabel: "Our base",
    routeDepartureBadge: "Marina del Sur · Las Galletas",
    routeHeroTitle: "Your experience aboard Leon starts here",
    routeHeroDesc: "Leon awaits you at Marina del Sur, beside the village and facing the Atlantic. A convenient meeting point where you can arrive, step aboard and start sailing.",

    helmPre: "The right arrangement for each service",
    helmTitle: "A skippered excursion or yacht rental with and without a skipper",
    helmDesc: "The private 6-hour excursion always takes place with the captain. For rentals of at least 3 days, you may hire a skipper or sail without one if you can provide the required experience and qualifications.",
    helmCaptainTitle: "Francesco Gestri, Leon's owner and skipper",
    helmCaptainDesc: "With more than 20 years at sea, Francesco is a qualified Merchant Navy skipper who personally hosts the experience. He speaks Spanish, Italian and English.",
    helmGuestTitle: "International qualification",
    helmGuestDesc: "He holds the Yacht Master Offshore Commercial qualification together with Italian and Spanish recreational sailing qualifications.",
    helmSafetyTitle: "Bareboat rental",
    helmSafetyDesc: "Available from 3 days, with six sleeping berths and subject to prior verification of the sailing experience and qualifications of the person who will command the yacht.",

    instructionPre: "Training aboard",
    instructionPriceLabel: "Training day",
    instructionPrice: "€200",
    instructionTax: "Published price · IGIC included",
    instructionSchedule: "From 9:00 to 17:00",

    secGaleriaPre: "The yacht",
    secGaleriaTitulo: "Meet Leon",
    secGaleriaDesc: "Explore every part of Leon, from the deck and sailing experience to the saloon, dining area and cabins. Every photograph shows the real yacht and the setting around your day at sea.",
    galeriaAbrir: "Open photograph",
    galeriaCerrar: "Close photograph",
    galeriaAnterior: "Previous photograph",
    galeriaSiguiente: "Next photograph",

    videoPre: "Leon in motion",
    videoTitle: "Sails, wind and Tenerife in a single frame",
    videoDesc: "A genuine aerial view of Leon sailing along Tenerife's south coast. Nothing staged: the blue Atlantic, the island's silhouette and the natural pace of a day under sail.",
    videoNote: "Real aerial footage of Leon in Tenerife",
    videoPlay: "Play video",
    videoPause: "Pause video",
    storyVisualAlt: "Leon sailing off the coast of Tenerife",

    reserveBandPre: "Direct booking",
    reserveBandTitle: "Your day at sea starts with a date",
    reserveBandDesc: "Choose a private 6-hour excursion, a rental of 3 days or more, or the training day. We reply personally with availability and conditions, with no middlemen.",
    reserveBandCalendar: "View availability",
    reserveBandWhatsapp: "Enquire on WhatsApp",
    reserveBandCall: "Call now",
    reserveHelpTitle: "Would you rather talk first?",
    reserveHelpDesc: "Message or call us. We will help you choose between the 6-hour excursion, a rental from 3 days and the training day.",
    reserveResponse: "Direct contact and a personal reply",

    calPre: "Start imagining your day",
    calTitulo: "Choose your experience. The calendar will do the rest.",
    calDesc: "Select the excursion, training day or rental and its duration first. The calendar will show only dates that can accommodate the full plan.",
    bookingPrivate: "The entire yacht for your group",
    bookingDirect: "Direct booking with no platform fees",
    bookingPersonal: "With or without a skipper, subject to experience and qualifications",
    bookingPromiseTitle: "Clear, direct and personal booking",
    bookingPromiseDesc: "No platforms and no automated replies. You speak directly with us from your first enquiry until the day you sail.",
    processOne: "Choose the service and, for a rental, enter the number of days you need.",
    processTwo: "Select a compatible date and enter your group size and plan details.",
    processThree: "Receive a clear proposal with options, price and next steps.",

    secHistoria: "About us",
    histSub: "We are Francesco Gestri and Maureen Lacchini. The sea is part of our story.",
    histP1: "We are husband and wife, and we met during a sailing holiday in Italy. Since then, sailing has become a way of life that we now share with our daughter Isabel and with guests who come to Tenerife looking for a more personal experience.",
    histP2: "Francesco, Leon's owner and skipper, brings more than 20 years of sailing experience together with his Merchant Navy and Yacht Master Offshore Commercial qualifications. Maureen brings warmth and close attention to the details that make every trip welcoming. Together, we want you to feel safe and truly at home aboard.",
    storySignature: "We are Francesco and Maureen. Welcome aboard Leon.",
    secInmo: "Tenerife, perhaps for longer",

    guidePre: "Before setting sail",
    guideTitle: "Everything you need for a comfortable day",
    guideDesc: "You will receive the final practical details once the trip is confirmed. In the meantime, these recommendations will help you arrive prepared and comfortable.",
    guideOneTitle: "Comfortable clothing",
    guideOneDesc: "Bring light clothing and a thin jacket. The temperature can feel different at sea even on a sunny day.",
    guideTwoTitle: "Suitable footwear",
    guideTwoDesc: "We recommend clean, flat shoes with non-slip soles. Please avoid heels and footwear that could mark the deck.",
    guideThreeTitle: "Sun protection",
    guideThreeDesc: "Sunscreen, sunglasses and a hat are essential. Add swimwear and a towel for any swimming stops.",
    guideFourTitle: "Arriving at the marina",
    guideFourDesc: "Please arrive around 15 minutes early. We will send the exact meeting point and access information once the booking is confirmed.",
    guideFiveTitle: "Seasickness and health",
    guideFiveDesc: "If you are prone to seasickness, ask a healthcare professional in advance about a suitable option and tell us about any relevant needs.",
    guideSixTitle: "Bags and identification",
    guideSixDesc: "A small, soft bag is best. Bring identification and let us know in advance about allergies, reduced mobility or special requirements.",

    faqPre: "Frequently asked questions",
    faqTitle: "Everything important, clearly explained",
    faqQ1: "Does selecting a date confirm the booking?",
    faqA1: "No. Selecting a date opens a no-obligation enquiry. We will confirm availability, the proposal, price and conditions before the booking is finalised.",
    faqQ2: "Where does Leon depart from?",
    faqA2: "Leon departs from Marina del Sur in Las Galletas. Once the trip is confirmed, we will send the exact meeting point and arrival information.",
    faqQ3: "Is the route decided in advance?",
    faqA3: "We prepare the route around your chosen service and interests. The final route is confirmed close to departure according to the wind and sea state.",
    faqQ4: "How do I receive options and pricing?",
    faqA4: "Choose a date and select the 6-hour excursion, a rental from 3 days or the training day. You can also message us directly on WhatsApp.",
    faqQ5: "Can I rent Leon without a skipper?",
    faqA5: "Yes, only for rentals of at least 3 days and provided you can demonstrate the required sailing experience and qualifications. The 6-hour excursion and training day take place with a captain or instructor aboard.",
    faqQ6: "What is included in the private excursion?",
    faqA6: "The published €600 price includes a six-hour excursion, captain, lunch, anchoring, snorkelling equipment, insurance, passenger charge and IGIC. It allows up to eight passengers plus the captain.",
    faqQ7: "What safety equipment does Leon carry?",
    faqA7: "Leon carries the equipment required by law: enough lifejackets for everyone, six self-inflating lifejackets for longer rentals, a liferaft, automatic EPIRB, flares, first-aid kit, fire extinguishers, lifebuoy and lifelines.",

    whatsappFloatEyebrow: "Have a question?",
    whatsappFloatLabel: "Message us on WhatsApp",

    ctaEyebrow: "Your next story begins here",
    ctaFinal: "When would you like to come aboard?",
    ctaDesc: "Tell us your preferred date, group size and the day you have in mind. We will turn it into a sailing proposal.",
    mobileCta: "View available dates",
    footerTagline: "Private sailing experiences from Marina del Sur, Tenerife.",
    footerContact: "Direct contact",
    avisoLegal: "Legal notice",
    privacidad: "Privacy",
    cookies: "Cookies",
  },
} as const;
